# Generated by Django 5.0.2 on 2024-02-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='receipe_descriprion',
            field=models.TextField(max_length=100),
        ),
    ]
