# Generated by Django 5.0.2 on 2024-02-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_alter_receipe_receipe_descriprion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='receipe_descriprion',
            new_name='receipe_description',
        ),
    ]
