# Generated by Django 5.0.2 on 2024-02-13 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_department_studentid_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='depaartment',
            new_name='department',
        ),
    ]
