# Generated by Django 5.0.2 on 2024-02-08 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_alter_receipe_receipe_descriprion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='image',
            new_name='receipe_image',
        ),
    ]
