# Generated by Django 5.0.2 on 2024-02-13 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0009_rename_depaartment_student_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_adress',
            new_name='student_address',
        ),
    ]
