# Generated by Django 5.0.2 on 2024-02-15 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0012_reportcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_report_card_generation')},
        ),
    ]
